language: julia
julia:
    - 0.5
    - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
    email: false
after_success:
    - julia -e 'cd(Pkg.dir("BasisMatrices")); Pkg.add("Coverage"); using Coverage; proc = process_folder(); Coveralls.submit(proc); Codecov.submit(proc)'
